Server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username : root
    password : GN2490

  jpa:
    hibernate:
        ddl-auto: update
    show-sql: true
